### ISSUE TITLE
Hover States

### ISSUE THREAD

**Issue by alemulli** [joshwalthall/game-of-life#1]
```  
  const mouseEnter = () => {
        tile.style.backgroundColor = hoverColor;
    };
    const mouseLeave = () => {
        _setTileColor();
    };
```

Much like I had said on the other repo accidentally, giving the tiles a class and handling the hoverstate with CSS would make the code a bit cleaner and require less javascript processing. It would allow you to cut out that snippit up there as well as lines 97 and 98 and have a shorter return on line 73. I'll make a PR tonight if this change is ok with you?

**Comment by joshwalthall** [comment]
I agree, I'd much rather style this with CSS. I tried that initially using the :hover selector, but couldn't get it to work for some reason so I must have been doing something wrong. Feel free to make a PR! I'd be happy to see how to do this piece in CSS instead.

**Comment by alemulli** [comment]
@joshwalthall  I can't figure out how to do a PR, do I need to be assigned to the issue, or added as a contributor on the repo?

**Comment by alemulli** [comment]
Nevermind I figured it out, I had to fork it.

**Comment by joshwalthall** [comment]
I'm glad you figured it out! I've never actually done a PR myself, so this is good practice for you and me both!
