### ISSUE TITLE
mouse enter/leave event listeners

### ISSUE THREAD

**Issue by alemulli** [joshwalthall/game-of-life#3]
```
                cellTile.addEventListener('mouseenter', newCell.mouseEnter);
                cellTile.addEventListener('mouseleave', newCell.mouseLeave);
```
Removing these could boost performance. It's tracking that event listener for every cell of the grid but its not needed for anything.

**Comment by joshwalthall** [comment]
Good catch! This was from when I was using DOM manipulation to change the color when hovering over the cell because at the time I couldn't get the CSS to work. This has been removed and will be reflected in the next commit. Thank you!
